### ISSUE TITLE
Failed to retrieve data node status via `get_data_node()`

### ISSUE THREAD

**Issue by hongyuanjia** [ideas-lab-nus/epwshiftr#80]
The LLNL ESGF Node has transferred to use the new Metagrid UI, which makes `get_data_node()` fail to parse the data node status. Workrounds include:

- Use the legacy interface from other federated ESGF Nodes
- Update the parse to handle Metagrid UI

**Comment by EHDD-EPIC** [comment]
Thanks for the workaround! Was having this issue earlier today.
